"""add ai analysis to tickets

Revision ID: 824afd96eadc
Revises: f341c465a1ed
Create Date: 2026-08-27 17:47:32.616084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '824afd96eadc'
down_revision: Union[str, Sequence[str], None] = 'f341c465a1ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('ai_category', sa.String(length=50), nullable=True))
    op.add_column('tickets', sa.Column('ai_priority', sa.String(length=50), nullable=True))
    op.add_column('tickets', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('ai_suggested_response', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'ai_suggested_response')
    op.drop_column('tickets', 'ai_summary')
    op.drop_column('tickets', 'ai_priority')
    op.drop_column('tickets', 'ai_category')
    # ### end Alembic commands ###
