"""add soft delete to tickets

Revision ID: f341c465a1ed
Revises: 876cd4149cc5
Create Date: 2026-08-27 10:48:31.715516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f341c465a1ed'
down_revision: Union[str, Sequence[str], None] = '876cd4149cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'deleted_at')
    # ### end Alembic commands ###
